Repository 0x61nas/Ayah-intellij, pull requests merged in 2023-01, with the labels that each got.

#13 Suport the 2022.3 build and fix some bugs
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/release.yml
  .idea/misc.xml
  build.gradle.kts
  settings.gradle.kts
Labels: size/L

#24 Improve the gradle build configs and crate the gradle properties file to separate constant values from codes
  .idea/dbnavigator.xml
  CHANGELOG.md
  README.md
  build.gradle.kts
  gradle.properties
  src/main/resources/META-INF/plugin.xml
Labels: size/L

#25 update changelog
  CHANGELOG.md
Labels: size/M

#26 Update the screenshots :D
  README.md
  screenshots/ayah-details_1.0.0.png
  screenshots/notification_1.0.0.png
  screenshots/settings_1.0.0.png
Labels: size/XS

#27 Create the base for .editorconfig
  .editorconfig
Labels: size/L

#11 Initially ،add PlayMode 🥰
  src/main/java/com/anas/intellij/plugins/ayah/NotificationTimerTask.java
Labels: size/M

#31 ci(Mergify): configuration update
  .mergify.yml
Labels: size/XS
